BAS_ASP/BAS_ASP/Models/Comment.cs
using System;

namespace BAS_ASP.Models
{
    public class Comment
    {
        public string id { get; set; }
        public DateTime createdAt { get; set; }
        public string body { get; set; }
        public int userId { get; set; }
        public int postId { get; set; }
        public int likes { get; set; }
    }
}

BAS_ASP/BAS_ASP/Models/Post.cs
using System;
using System.Collections.Generic;

namespace BAS_ASP.Models
{
    public class Post
    {
        public string id { get; set; }
        public DateTime createdAt { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public int userId { get; set; }
        public int likes { get; set; }
        public List<Comment> comments { get; set; }
    }
}

BAS_ASP/BAS_ASP/Models/Todo.cs
using System;

namespace BAS_ASP.Models
{
    public class Todo
    {
        public string id { get; set; }
        public DateTime createdAt { get; set; }
        public string name { get; set; }
        public bool isComplete { get; set; }
        public int userId { get; set; }

    }
}

BAS_ASP/BAS_ASP/Models/User.cs
using System;
using System.Collections.Generic;

namespace BAS_ASP.Models
{
    public class User
    {
        public string id { get; set; }
        public DateTime createdAt { get; set; }
        public string name { get; set; }
        public string avatar { get; set; }
        public List<Todo> todos { get; set; }
        public List<Post> posts { get; set; }
    }
}

BAS_ASP/BAS_ASP/Controllers/PostController.cs
using BAS_ASP.BusinessLogic;
using Microsoft.AspNetCore.Mvc;

namespace BAS_ASP.Controllers
{
    public class PostController:Controller
    {
        PostBL postBL;

        public PostController()
        {
            postBL = new PostBL();
        }

        public IActionResult Index(string id)
        {
            return View(postBL.GetPostById(id));
        }

        public IActionResult GetAllPost()
        {
            return View(postBL.GetAllPost());
        }
    }
}

BAS_ASP/BAS_ASP/Controllers/TodoController.cs
using BAS_ASP.BusinessLogic;
using Microsoft.AspNetCore.Mvc;

namespace BAS_ASP.Controllers
{
    public class TodoController:Controller
    {
        TodoBL todoBL;

        public TodoController()
        {
            todoBL = new TodoBL();
        }

        public IActionResult Index(string id)
        {
            return View(todoBL.GetTodoById(id));
        }
    }
}

BAS_ASP/BAS_ASP/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using BAS_ASP.BusinessLogic;

namespace BAS_ASP.Controllers
{
    public class UserController:Controller
    {
        UserBL userBL;

        public UserController()
        {
            userBL = new UserBL();
        }

        public IActionResult Index(string id)
        {
            return View(userBL.GetUserById(id));
        }

        //1
        public IActionResult GetAmountOfCommentsByUserId(string id)
        {
            return View(userBL.GetAmountOfCommentsByUserId(id));
        }
              
        //2
        public IActionResult AllComments(string id, int length)
        {
            return View(userBL.GetAllCommentsByUserId(id, length));
        }

        //3
        public IActionResult CompletedTodos(string id)
        {
            return View(userBL.GetTodosByUserId(id));
        }

        //4
        public IActionResult SortedUsers()
        {
            return View(userBL.GetListOfUsers());
        }

        //5
        public IActionResult UserInformation(string id, int length)
        {
            return View(userBL.GetUserInformation(id, length));
        }

        //6
        public IActionResult PostInformation(string id, int length)
        {
            return View(userBL.GetPostInformation(id, length));
        }
    }
}

BAS_ASP/BAS_ASP/Views/Post/GetAllPost.cshtml
@model List<BAS_ASP.DTO.PostDTO>
@{
    ViewData["Title"] = "Home page";
    ViewData["Description"] = "The home page of my website";
}

@foreach (var post in Model)
{
    <div class="card mb-4">
        <div>
            <img src=@post.user.avatar alt="avatar" />
            <span class="ml-2">@Html.ActionLink(@post.user.name, "Index", "User", new { @post.user.id })</span>

        </div>

        <div class="card-body">
            <div class="card">
                <h3 class="card-header">@post.title</h3>

                <div class="card-body">
                    @post.body
                </div>

                <div class="d-flex justify-content-between p-3 ">
                    <div>
                        <time>@post.createdAt</time>
                    </div>
                    <div>
                        <i class="fas fa-heart"></i>
                        @post.likes
                    </div>
                </div>
                <div>
                    <p>
                        <button class="btn btn-primary ml-2" type="button" data-toggle="collapse" data-target=@string.Concat("#1", @post.id) aria-expanded="false" aria-controls="collapseTable">
                            Comments
                        </button>
                    </p>
                    <div class="collapse " id=@string.Concat("1", @post.id)>
                        <div class="card card-body">
                            @if (@post.comments != null)
                            {
                                    @foreach (var comment in @post.comments)
                                    {
                                     
                                            <div class="card">
                                                <div class="card-body">
                                                    @comment.body
                                                </div>

                                                <div class="d-flex justify-content-between p-3 ">
                                                    <div>
                                                        <time>@comment.createdAt</time>
                                                    </div>
                                                    <div>
                                                        <i class="fas fa-heart"></i>
                                                        @comment.likes
                                                    </div>
                                                </div>
                                            </div>
                                       
                                    }                              
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @*Insert any script tags for this page here*@
}

BAS_ASP/BAS_ASP/Views/Post/Index.cshtml
@model Post
@{
    ViewData["Title"] = "Post Detail";
    ViewData["Description"] = "Detail of post";
}

<div class="card">
    <h3 class="card-header">@Model.title</h3>

    <div class="card-body">
        @Model.body
    </div>

    <div class="d-flex justify-content-between p-3 ">
        <div>
            <time>@Model.createdAt</time>
        </div>
        <div>
            <i class="fas fa-heart"></i>
            @Model.likes
        </div>
    </div>


 </div>

BAS_ASP/BAS_ASP/Views/Todo/Index.cshtml
@model Todo
@{
    ViewData["Title"] = "Todo Detail";
    ViewData["Description"] = "Detail of todo";
}

<table  class="table table-striped">
    <th>Created at</th>
    <th>Name</th>
    <th>Is completed</th>
        <tr>
            <td>@Model.createdAt</td>
            <td>@Model.name</td>
            <td>@Model.isComplete</td>
        </tr>
</table>

BAS_ASP/BAS_ASP/Views/User/AllComments.cshtml
@model IEnumerable<Comment>
@{
    ViewData["Title"] = "Users' comments";
    ViewData["Description"] = "Get sers' all comments";
}

@using (Html.BeginForm())
{
    <p>
        User id: @Html.TextBox("id") <br />
    </p>
    <p>
        Length: @Html.TextBox("length") <br />
        <input class="btn btn-dark mt-3" type="submit" value="Search" />
    </p>
} 

<table class="table table-striped">
    <th>Created at</th>
    <th>Body</th>
    <th>Likes</th>

    @foreach (var comment in Model)
    {
        <tr>
            <td>@comment.createdAt</td>
            <td>@comment.body</td>
            <td>@comment.likes</td>
    </tr>

    }
</table>

BAS_ASP/BAS_ASP/Views/User/CompletedTodos.cshtml
@model IEnumerable<Todo>
@{
    ViewData["Title"] = "Completed todos";
    ViewData["Description"] = "Get sers' all comments";
}

@using (Html.BeginForm())
{
    <p>
        User id: @Html.TextBox("id") <br />
        <input class="btn btn-dark mt-3" type="submit" value="Search" />
    </p>
}

<table class="table table-striped">
    <th>Id</th>
    <th>Name</th>

    @foreach (var todo in Model)
    {
        <tr>
            <td>@todo.id</td>
            <td>@Html.ActionLink(todo.name, "Index","Todo", new { @todo.id })</td>
        </tr>

    }
</table>

BAS_ASP/BAS_ASP/Views/User/GetAmountOfCommentsByUserId.cshtml
@model List<BAS_ASP.DTO.PostCommentsDTO>
@{
    ViewData["Title"] = "Amount of comments ";
    ViewData["Description"] = "Amount of comments by user id";
}

@using (Html.BeginForm())
{
    <p>
        User id: @Html.TextBox("id") <br />
        <input class="btn btn-dark mt-3" type="submit" value="Search" />
    </p>
}

@foreach (var p in Model)
{
    <table class="table table-striped mb-4">
        <tr>
            <th> Post </th>
            <td>
                <div>                    
                         @Html.ActionLink(@p.post.title, "Index", "Post", new { @p.post.id })
                </div>
                <div>
                    @p.post.body
                </div>
                <div>
                    <i class="fas fa-heart"></i>
                    @p.post.likes
                </div>
                <div>
                    @p.post.createdAt
                </div>

            </td>
        </tr>

        <tr>
            <th> Ammoubt of comments </th>
            <td> @p.amountOfComments </td>
</tr>
    </table>
}

BAS_ASP/BAS_ASP/Views/User/Index.cshtml
@model User
@{
    ViewData["Title"] = "User Detail";
    ViewData["Description"] = "Detail of user";
}

<div>
        <img src=@Model.avatar alt="avatar" />

        <h2 class="ml-2">@Model.name</h2> <br />
        <span class="ml-2">@Model.createdAt</span>  

</div>

BAS_ASP/BAS_ASP/Views/User/PostInformation.cshtml
@model BAS_ASP.DTO.PostInformationDTO
@{
    ViewData["Title"] = "Post information";
    ViewData["Description"] = "Get sers' all comments";
}


@using (Html.BeginForm())
{
    <p>
        User id: @Html.TextBox("id") <br />
    </p>
    <p>
        Length: @Html.TextBox("length") <br />
        <input class="btn btn-dark mt-3" type="submit" value="Search" />
    </p>
}


@if (Model != null)
{
    <table  class="table table-striped">
        <tr>
            <th> Post </th>
            <td>
                <div>
                    @Html.ActionLink(@Model.Post.title, "Index", "Post", new { @Model.Post.id })
                </div>
                <div>
                    @Model.Post.body
                </div>
                <div>
                    <i class="fas fa-heart"></i>
                    @Model.Post.likes
                </div>
                <div>
                    @Model.Post.createdAt
                </div>
                
            </td>
        </tr>
@if (Model.LongerComment != null)
{
        <tr>
            <th> Longer comment of post </th>
            <td> 
                <div>
                   @Model.LongerComment.body
                </div>
                <div>
                    <i class="fas fa-heart"></i>
                   @Model.LongerComment.likes 
                </div>
                <div>
                    @Model.LongerComment.createdAt
                </div>
            </td>
        </tr>
}
@if (Model.LikerComment != null)
{
        <tr>
            <th> liker comment of post </th>
            <td>
                <div>
                    @Model.LikerComment.body
                </div>
                <div>
                    <i class="fas fa-heart"></i>
                    @Model.LikerComment.likes
                </div>
                <div>
                    @Model.LikerComment.createdAt
                </div>  
            </td>
        </tr>
}
        <tr>
            <th>Amount of comments</th>
            <td>
                @Model.AmountOfComments
            </td>
        </tr>
    </table>
}

BAS_ASP/BAS_ASP/Views/User/SortedUsers.cshtml
@model IEnumerable<User>
@{
    ViewData["Title"] = "";
    ViewData["Description"] = "The home page of my website";
}

<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>CreatedAt</th>
        <th>Name</th>
        <th>Todos</th>
        <th>Posts</th>
    </tr>
        
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.id</td>
            <td>@user.createdAt</td>
            <td>@Html.ActionLink(@user.name, "Index", new { @user.id })</td>

            <td>
                <p>
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target=@string.Concat("#", @user.id) aria-expanded="false" aria-controls="collapseTable">
                        All todos
                    </button>
                </p>
                <div class="collapse" id=@user.id>
                    <div class="card card-body">
                       <table class="table table-striped">
                                <tr>
                                    <th>Id</th>
                                    <th>Created at</th>
                                    <th>Name</th>
                                    <th>Is completed</th>
                                </tr>


                                @foreach (var todo in @user.todos)
                                {
                                    <tr>
                                        <td>@todo.id</td>
                                        <td>@todo.createdAt</td>
                                        <td>@Html.ActionLink(@todo.name, "Index","Todo", new { @todo.id })</td>
                                        <td>@todo.isComplete</td>
                                    </tr>
                                }
                       </table>
                    </div>
                </div>
            </td>

            <td>
                <p>
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target=@string.Concat("#1", @user.id) aria-expanded="false" aria-controls="collapseTable">
                        All posts
                    </button>
                </p>
                <div class="collapse" id=@string.Concat("1", @user.id)>
                    <div class="card card-body">
                        <table class="table table-striped">
                            <tr>
                                <th>Id</th>
                                <th>Created at</th>
                                <th>Title</th>
                                <th>Body</th>
                                <th>Likes</th>
                            </tr>


                            @foreach (var post in @user.posts)
                            {
                                <tr>
                                    <td>@post.id</td>
                                    <td>@post.createdAt</td>
                                    <td>>@Html.ActionLink(@post.title, "Index", "Post", new { @post.id })</td>
                                    <td>@post.body</td>
                                    <td>@post.likes</td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </td>

        </tr>
    }
</table>
@section Scripts {
    @*Insert any script tags for this page here*@
}

BAS_ASP/BAS_ASP/Views/User/UserInformation.cshtml
@model BAS_ASP.DTO.UserInformationDTO
@{
    ViewData["Title"] = "User information";
    ViewData["Description"] = "Get sers' all comments";
}

@using (Html.BeginForm())
{
    <p>
        User id: @Html.TextBox("id") <br />
    </p>
    <p>
        Length: @Html.TextBox("length") <br />
        <input class="btn btn-dark mt-3" type="submit" value="Search" />
    </p>
}

@if (Model != null)
{
    <table class="table table-striped">
        <tr>
            <th> User </th>
            <td class="d-flex">
                <img src=@Model.User.avatar class="img-circle" alt="avatar" />
                <div class="p-3">
                    <div>
                        @Model.User.name
                    </div>
                    <div>
                        @Model.User.createdAt
                    </div>
                </div>


            </td>
        </tr>
        <tr>
            <th> Last post </th>
            <td>
                <div>           
                    @Html.ActionLink(@Model.LastPost.title, "Index", "Post", new { @Model.LastPost.id })
                </div>
                <div>
                    @Model.LastPost.body
                    </div>
                <div>
                    <i class="fas fa-heart"></i>
                    @Model.LastPost.likes
                    </div>
</td>
        </tr>
        <tr>
            <th> Amount of comment</th>
            <td>
                @Model.AmountOfComm
            </td>
        </tr>
        <tr>
            <th>Uncompleted tasks</th>
            <td>
                @Model.UncompletedTasks
            </td>
        </tr>
        <tr>
            <th>Popular post by comments </th>
            <td>
                <div>
                    @Html.ActionLink(@Model.PopularPostByComm.title, "Index", "Post", new { @Model.LastPost.id })
                </div>
                <div>
                    @Model.PopularPostByComm.body
                </div>
                <div>
                    <i class="fas fa-heart"></i>
                    @Model.PopularPostByComm.likes
                </div>
            </td>
        </tr>
        <tr>
            <th>Popular post by likes </th>
            <td>
                <div>
                    @Html.ActionLink(@Model.PopularPostByLikes.title, "Index", "Post", new { @Model.LastPost.id })
                </div>
                <div>
                    @Model.PopularPostByLikes.body
                </div>
                <div>
                    <i class="fas fa-heart"></i>
                    @Model.PopularPostByLikes.likes
                </div>
            </td>
        </tr>
    </table>
}

BAS_ASP/BAS_ASP/Views/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - BAS_ASP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="@ViewData["Description"]" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="#" rel="stylesheet" />
</head>
<body>

    <div class="wrapper">
        <header role="banner">
            <nav class="container">
                <ul>
                    <li><a asp-controller="Post" asp-action="GetAllPost">Home</a></li>
                    <li><a asp-controller="User" asp-action="GetAmountOfCommentsByUserId">Comments by userId</a></li>
                    <li><a asp-controller="User" asp-action="AllComments">All Comments</a></li>
                    <li><a asp-controller="User" asp-action="CompletedTodos">Completed todos</a></li>
                    <li><a asp-controller="User" asp-action="SortedUsers">Sorted users</a></li>
                    <li><a asp-controller="User" asp-action="UserInformation">User information</a></li>
                    <li><a asp-controller="User" asp-action="PostInformation">Post information</a></li>
                </ul>
            </nav>
        </header>

        <main class="container">
            <h1>@ViewData["Title"]</h1>
            @RenderBody()
        </main>
    </div>

    <footer>
        @*<div class="container">
            <span>&copy; @DateTime.Now.Year - BAS_ASP</span>
        </div>*@
    </footer>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>